params:
  mode: visualize # train, test, inference, visualize
  e: 100
  bs: 256
  ss: 88 # На слабых ПК лучше ставить не более 32
  path-models: models/
  path-checkpoint: 260121_100-256-88_1-0.0000.pt
  path-data: data/
  path-infers: 12345.jpeg
  path-labels: data/labels.txt
  dataset-size: 397098665
  dataset-splits: 0.7-0.2-0.1 # суммарно д.б. = 1.0
  infer-output: std # mpl (GUI) либо std (текст)
