name: paysage-classification
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311haa0f9ac_1
  - brotlicffi=1.1.0.0=py311hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - click=8.2.1=py311h06a4308_1
  - contourpy=1.3.1=py311hdb19cb5_0
  - cuda-cccl_linux-64=12.8.90=h06a4308_1
  - cuda-crt-dev_linux-64=12.8.93=h06a4308_3
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart-dev=12.8.90=hbdd6827_0
  - cuda-cudart-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart-static=12.8.90=hbdd6827_0
  - cuda-cudart-static_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-cuobjdump=12.8.90=h5b7f43c_1
  - cuda-cupti=12.8.90=hbdd6827_1
  - cuda-driver-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-nvcc=12.8.93=h02f8991_2
  - cuda-nvcc-dev_linux-64=12.8.93=he2511ca_3
  - cuda-nvcc-impl=12.8.93=hd1a145a_3
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvcc_linux-64=12.8.93=h2f703a9_2
  - cuda-nvdisasm=12.8.90=h5b7f43c_1
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-nvtx=12.8.90=hbdd6827_1
  - cuda-nvvm-dev_linux-64=12.8.93=h06a4308_3
  - cuda-nvvm-impl=12.8.93=hbdd6827_3
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-version=12.8=h30beaf8_3
  - cudnn=9.15.1.9=h4a770f4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h7354ed3_1
  - ffmpeg=6.1.1=hecf7045_5
  - filelock=3.20.0=py311h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py311hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fsspec=2025.10.0=py311h7040dfc_0
  - gcc_impl_linux-64=14.3.0=h4943218_4
  - gcc_linux-64=14.3.0=hda73cce_12
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=14.3.0=he634eba_4
  - gxx_linux-64=14.3.0=hca8765c_12
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py311h06a4308_0
  - importlib-metadata=8.5.0=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - kiwisolver=1.4.8=py311h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libcublas=12.8.4.1=hbdd6827_1
  - libcudnn=9.15.1.9=ha36b8be_0
  - libcudnn-dev=9.15.1.9=h1079e53_0
  - libcufft=11.3.3.83=hbdd6827_1
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.9.90=hbdd6827_1
  - libcusolver=11.7.3.90=hbdd6827_1
  - libcusparse=12.5.8.93=hbdd6827_1
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=he7458c1_104
  - libgcc-ng=15.2.0=h166f726_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libllvm19=19.1.7=h465586c_5
  - libmlir19=19.1.7=hfbf14b3_2
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.8.93=hbdd6827_1
  - libnvjpeg=12.3.5.92=hbdd6827_1
  - libogg=1.3.5=h27cfd23_1
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsanitizer=14.3.0=hd4faa28_4
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=he7458c1_104
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=gpu_cuda124_hf726350_304
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - lit=20.1.8=py311h06a4308_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.7.1=ha545f22_0
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.6=py311h06a4308_1
  - matplotlib-base=3.10.6=py311h71dd3da_1
  - mesalib=25.1.5=h31e3550_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - nccl=2.28.9.1=h7b78073_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.5=py311h06a4308_0
  - numexpr=2.11.0=py311hf4471f9_0
  - numpy=2.0.1=py311h08b1b3b_1
  - numpy-base=2.0.1=py311hf175353_1
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - opentelemetry-api=1.37.0=py311h06a4308_0
  - packaging=25.0=py311h06a4308_1
  - pandas=2.3.3=py311h23c847b_1
  - pcre2=10.46=hf426167_0
  - pillow=11.1.0=py311hac6e08b_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py311h06a4308_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=6.9.1=py311hc79087c_0
  - pyqt6-sip=13.10.2=py311hee96239_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.5.1=gpu_cuda124_py311hfee4293_304
  - pytz=2025.2=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - qtbase=6.9.2=hd13baf8_5
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_0
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - setuptools=80.9.0=py311h06a4308_0
  - sip=6.12.0=py311h7934f7d_0
  - six=1.17.0=py311h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=py311h06a4308_1
  - sysroot_linux-64=2.28=h3108a97_1
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=cuda124py311hf5dacad_100
  - torchvision=0.20.1=cuda124py311ha0e159c_102
  - tornado=6.5.1=py311h5eee18b_0
  - tqdm=4.67.1=py311h7040dfc_1
  - triton=3.1.0=cuda124py311hac27663_3
  - typing-extensions=4.15.0=py311h06a4308_0
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.45.1=py311h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.21.0=py311h06a4308_0
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiohttp-retry==2.9.1
      - aiosignal==1.4.0
      - amqp==5.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asyncssh==2.22.0
      - atpublic==7.0.0
      - attrs==25.4.0
      - billiard==4.2.4
      - black==25.12.0
      - bleach==6.3.0
      - celery==5.6.2
      - cfgv==3.5.0
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - colorama==0.4.6
      - configobj==5.0.9
      - cryptography==43.0.3
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dpath==2.2.0
      - dulwich==1.0.0
      - dvc==3.66.1
      - dvc-data==3.18.2
      - dvc-gdrive==3.0.1
      - dvc-http==2.32.0
      - dvc-objects==5.2.0
      - dvc-render==1.0.2
      - dvc-studio-client==0.22.0
      - dvc-task==0.40.2
      - entrypoints==0.4
      - flake8==7.3.0
      - flatten-dict==0.4.2
      - flufl-lock==9.0.0
      - frozenlist==1.8.0
      - funcy==2.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.47.0
      - google-auth-httplib2==0.3.0
      - googleapis-common-protos==1.72.0
      - grandalf==0.8
      - grpcio==1.76.0
      - gto==1.9.0
      - httplib2==0.31.1
      - hydra-core==1.3.2
      - identify==2.6.15
      - isort==7.0.0
      - iterative-telemetry==0.0.10
      - joblib==1.5.2
      - kombu==5.6.2
      - librt==0.7.7
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - nodeenv==1.10.0
      - oauth2client==4.1.3
      - omegaconf==2.3.0
      - orjson==3.11.5
      - pathspec==0.12.1
      - platformdirs==4.5.1
      - pre-commit==4.5.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.0
      - psutil==7.2.1
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycodestyle==2.14.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydot==4.0.1
      - pydrive2==1.21.3
      - pyflakes==3.4.0
      - pygit2==1.19.1
      - pygments==2.19.2
      - pygtrie==2.5.0
      - pyopenssl==24.2.1
      - python-dotenv==1.2.1
      - python-slugify==8.0.4
      - pytokens==0.3.0
      - rich==14.2.0
      - rsa==4.9.1
      - ruamel-yaml==0.19.1
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - scmrepo==3.6.1
      - semver==3.0.4
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.8.0
      - smmap==5.0.2
      - sqltrie==0.11.2
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tomlkit==0.14.0
      - typer==0.21.1
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - uritemplate==4.2.0
      - vine==5.1.0
      - virtualenv==20.35.4
      - voluptuous==0.16.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - werkzeug==3.1.5
      - yarl==1.22.0
      - zc-lockfile==4.0
prefix: /home/andrey/miniconda3/envs/paysage-classification
